name: 自动部署Docs

run-name: 来自 @${{ github.actor }} 的部署
# 触发条件
on:
  push:
    branches:
      - master
# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: 拉取代码
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          # 拉取深度为 0，这样就可以拉取所有分支的 commit 记录
          # fetch-depth: 0

      - name: 安装 node 环境
        # node 环境 >= 16.18.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0
          registry-url: https://registry.npm.taobao.org

      - name: 检查环境
        # 判断是否存在 pnpm，如果不存在就安装
        run: |
          if [ ! -x "$(command -v pnpm)" ]; then
            npm install -g pnpm
          fi

      - name: 安装依赖
        run: pnpm install --no-frozen-lockfile
      # 打包

      - name: 打包
        run: pnpm docs:build

      # 部署到 GitHub Pages
      - name: 部署，迁移至 gh-pages 分支
        # 使用别人写好的一个 action
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 这里的 ACCESS_TOKEN 名字需要和下文中的相对应
          ACCESS_TOKEN: ${{ secrets.SECRET_DOCS }}

          FOLDER: docs/.vitepress/dist

          # 打包后的文件部署到哪个分支上
          BRANCH: gh-pages

          # 保留历史记录
          # PERSIST_HISTORY: true

          # 保留 CNAME 文件
          # PERSIST_CNAME: true

        # 发送通知
      - name: 发送通知 - 邮箱
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.qq.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.event.head_commit.message }}
          body: |
            ${{ github.event.head_commit.message }}
            ${{ github.event.head_commit.url }}
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/plain
